### ISSUE TITLE
Leaving a dungeon shuts down server

### ISSUE THREAD

**Issue by Cr0wmaster** [gildedgames/aether-issues#424] opened 2015-02-24 14:35 UTC
This happens on multiplayer. When any player leaves dunegon, whole server shuts down. I will post crash report later.

**Comment by Collin1971** [comment] 2015-02-24 18:36
Possible duplicate of issue #387.

Please re-open this issue when you obtain the crash log.

**Closed by Collin1971** 2015-02-24 18:36 UTC
