### ISSUE TITLE
Skyroot Door Glitch.

### ISSUE THREAD

**Issue by SarvesPro** [gildedgames/aether-issues#532] opened 2015-08-24 12:10 UTC
I'm very new to the mod and when I was building a home in the aether, I misplaced my door. I used my Zanite Axe on the top half and got back 2 doors. Then I tested breaking the bottom part and I only got one. I'm wondering if this is a glitch or if it's intentional. Well I'm just gonna doop doors for no reason I guess ;)

**Comment by Collin1971** [comment] 2015-08-24 12:38
Duplicate of #510.

**Closed by Collin1971** 2015-08-24 12:38 UTC
