### ISSUE TITLE
Aether 2 + Tinkers Construct Health Canister + changing dimension = as much hp as you want

### ISSUE THREAD

**Issue by Razorskills** [gildedgames/aether-issues#491] opened 2015-05-03 23:04 UTC
Summary of the issue:
Place some tinkers construct heart canisters on the proper slot, then let your health regenerate 1 heart for each canister you added. Then go through a portal. (Nether Portal, tp with a command, any kind of dimension change) then watch your health increase by a lot. Each teleport increases the health. (I actually forgot to test telporting to a location in the same demension, I will try that in a bit)

Here is a video showing the issue:
https://www.youtube.com/watch?v=fIUmeoe7wrk&feature=youtu.be

I have recently tested this on forge 1388 and 1399

But I do remember this being an issue in 1.6 it was reported, but I thought it was fixed. Yesterday we found a way to reproduce the bug, and that it is still present in the latest version.

Here is a picture of a player.dat file for a player that has had this happen to them. I can manually fix it by changing those value back to 20. But as soon as they teleport, it gives them more health.

I am guessing that something in the aether 2 is doing something to the generic.maxHealth attribute

![aetherii tinkersconstructheartcanisters](https://cloud.githubusercontent.com/assets/6126264/7447373/0e2c788c-f1b6-11e4-99a0-0214cc880a84.PNG)

Also the heart canisters can only be in a stack of 10. So then you should only be able to get 40 hp total using tinkers

EDIT: I forgot to open this one aswell in NBT-Explorer it might also be useful information
![tconstruct heartcanister](https://cloud.githubusercontent.com/assets/6126264/7447494/c32bca22-f1ba-11e4-92a6-bd73356c7b59.PNG)

**Comment by Razorskills** [comment] 2015-05-03 23:43
Crap this is a duplicate of #489 that I didn't see

**Comment by CherryHotaling** [comment] 2015-05-04 01:31
Duplicate of: https://github.com/gildedgames/aether-issues/issues/459

**Comment by Razorskills** [comment] 2015-05-04 03:22
ah didn't see that one either. obviously its a big issue though..

**Closed** 2015-05-05 12:00 UTC
Labels: duplicate
