### ISSUE TITLE
Multiplayer, Slider crashes server

### ISSUE THREAD

**Issue by CrimsonHeroA8** [gildedgames/aether-issues#465] opened 2015-03-11 22:21 UTC
Player: SirArias

On xjon.me:25565 immediately after killing the Slider boss the game crashed. it seems that as long as I am inside that dungeon it will crash my game forcing me to launch again. I am not able to join the server because when ever I do it will crash.
Information I thought that might help
*The Slider was killed by a player that did not enter the dungeon properly. (use of commands)
*The Slider was outside of the boss room
*Three players fought together to kill the Slider

I believe that the problem is that players who didn't enter the dungeon via totem will mess up the game when making the final blow on the Slider boss. (also happens with mini bosses but its minor, killing a mini boss without entering the dungeon via totem will not give the player a key as seen in top right corner)

Erm, Help me. i need to be teleported outside the dungeon somehow so that i don't crash.

**Comment by Collin1971** [comment] 2015-03-11 22:23
We _DO NOT_ provide support for any clouds on the Cloud Network. We have no control over them.

We had to reupload our jars right after we released 1.7.10-1.2 due to a bug. Please try re-downloading the Aether II and see if the issue still persists.

**Comment by Collin1971** [comment] 2015-03-11 22:24
Duplicate of #463.

**Closed by Collin1971** 2015-03-11 22:23 UTC
