### ISSUE TITLE
Altar crashes client

### ISSUE THREAD

**Issue by Cr0wmaster** [gildedgames/aether-issues#448] opened 2015-03-02 08:07 UTC
Multiplayer bug: When someone puts item (not ambrosium) to altar, every player around get client crash (players far away dont get crash). Player who put something to altar dont get crash.

**Comment by xJonL** [comment] 2015-03-02 20:36
Could you provide us with a crashlog?

**Comment by Cr0wmaster** [comment] 2015-03-03 19:45
https://gist.github.com/Cr0wmaster/22ad4119a4a909cfe6df#file-gistfile1-txt

**Comment by Collin1971** [comment] 2015-03-03 23:15
Duplicate of #441.

**Closed by Collin1971** 2015-03-03 23:15 UTC
