### ISSUE TITLE
Crach server during spanw Blue Moa by the incubator

### ISSUE THREAD

**Issue by GwenhaelDevos** [gildedgames/aether-issues#455] opened 2015-03-05 22:01 UTC
On Linux(Ubuntu server  14.04) :
- Server ForgeInstaller for 1.7.10 (recommanded)
- Aether II (downlaod on official website)

The server crach during spanw Blue Moa by the incubator, i try to restart and immediatly again crached.

On Windows(2K8R2 GUI) :

- Server ForgeInstaller for 1.7.10(recommanded and another on Beta)
- Aether II (downlaod on official website)

same problème on recommanded and beta

> ---- Minecraft Crash Report ----
>// There are four lights!
>
>Time: 05/03/15 15:31
>Description: Ticking block entity
>
>java.lang.NullPointerException: Ticking block entity
>	at >net.aetherteam.aether.tile_entities.TileEntityIncubator.func_145845_h(TileEntityIncubator.java:222)
>	at net.minecraft.world.World.func_72939_s(World.java:1939)
>	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
>	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
>	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
>	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
>	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
>	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
>
>
>A detailed walkthrough of the error, its code path and all known details is as follows:
>---------------------------------------------------------------------------------------
>
>-- Head --
>Stacktrace:
>	at >net.aetherteam.aether.tile_entities.TileEntityIncubator.func_145845_h(TileEntityIncubator.java:222)
>
>-- Block entity being ticked --
>Details:
>	Name: Incubator // net.aetherteam.aether.tile_entities.TileEntityIncubator
>	Block type: ID #183 (tile.incubator // net.aetherteam.aether.blocks.BlockIncubator)
>	Block data value: 2 / 0x2 / 0b0010
>	Block location: World: (-848,64,-69), Chunk: (at 0,4,11 in -53,-5; contains blocks -848,0,-80 to >-833,255,-65), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
>	Actual block type: ID #183 (tile.incubator // net.aetherteam.aether.blocks.BlockIncubator)
>	Actual block data value: 2 / 0x2 / 0b0010
>Stacktrace:
>	at net.minecraft.world.World.func_72939_s(World.java:1939)
>	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
>
>-- Affected level --
>Details:
>	Level name: world
>	All players: 1 total; [EntityPlayerMP['shishui83590'/39275, l='world', x=-844,18, y=64,00, >z=-75,00]]
>	Chunk stats: ServerChunkCache: 781 Drop: 0
>	Level seed: -3157207978826762043
>	Level generator: ID 00 - default, ver 1. Features enabled: true
>	Level generator options: 
>	Level spawn location: World: (84,64,256), Chunk: (at 4,4,0 in 5,16; contains blocks 80,0,256 to >95,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
>	Level time: 2245878 game time, 31815 day time
>	Level dimension: 0
>	Level storage version: 0x04ABD - Anvil
>	Level weather: Rain time: 94886 (now: false), thunder time: 57767 (now: false)
>	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
>Stacktrace:
>	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
>	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
>	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
>	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
>	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
>
>-- System Details --
>Details:
>	Minecraft Version: 1.7.10
>	Operating System: Windows Server 2008 R2 (amd64) version 6.1
>	Java Version: 1.8.0_31, Oracle Corporation
>	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>	Memory: 344903336 bytes (328 MB) / 1015545856 bytes (968 MB) up to 2863661056 bytes >(2731 MB)
>	JVM Flags: 2 total; -Xms1G -Xmx3G
>	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
>	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 6 mods loaded, 6 mods >active
>	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) >Unloaded->Constructed->Pre-
>initialized->Initialized->Post->initialized->Available->Available->Availa>ble->Available
>	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291-universal.jar) >Unloaded->Constructed->Pre-initialized->Initialized->Post-
>initialized->Available->Available->Available->Available
>	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291-universal.jar) >Unloaded->Constructed->Pre-initialized->Initialized->Post-
>initialized->Available->Available->Available->Available
>	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) >Unloaded->Constructed->Pre-initialized->Initialized->Post-
>initialized->Available->Available->Available->Available
>	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar) >Unloaded->Constructed->Pre-initialized->Initialized->Post-
>initialized->Available->Available->Available->Available
>	aether{Alpha 1.7.10-1.1} [Aether II] (aether.jar) Unloaded->Constructed->Pre-
>initialized->Initialized->Post-initialized->Available->Available->Available->Available
>	Profiler Position: N/A (disabled)
>	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>	Player Count: 1 / 10; [EntityPlayerMP['shishui83590'/39275, l='world', x=-844,18, y=64,00, >z=-75,00]]
>	Is Modded: Definitely; Server brand changed to 'fml,forge'
>	Type: Dedicated Server (map_server.txt)

PS : Sorry if my english as not very well. I look forward to future fixes, this mod is great!

**Comment by Collin1971** [comment] 2015-03-05 22:12
Duplicate of #443 (similar to #441).

**Closed by Collin1971** 2015-03-05 22:12 UTC
