### ISSUE TITLE
Game Closes Upon Loading World

### ISSUE THREAD

**Issue by Psiiche** [gildedgames/aether-issues#567] opened 2015-10-12 13:05 UTC
I have a single player LAN world that I have successfully used for the past couple weeks, but last night it started closing the game upon trying to load the world. No significant changes were made within the timespan. The only mods I am using are the ones that are provided with Aether 2.

Here is the contents of the most recent crash report.

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 10/12/15 8:50 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.aetherteam.aether.client.renders.entities.player.RenderPlayerAether.renderGloves(RenderPlayerAether.java:74)
	at net.aetherteam.aether.client.renders.entities.player.RenderPlayerAether.renderHand(RenderPlayerAether.java:509)
	at net.aetherteam.aether.client.ClientGuiListener.onRenderHand(ClientGuiListener.java:67)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_31_ClientGuiListener_onRenderHand_RenderHandEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:266)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1358)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.aetherteam.aether.client.renders.entities.player.RenderPlayerAether.renderGloves(RenderPlayerAether.java:74)
	at net.aetherteam.aether.client.renders.entities.player.RenderPlayerAether.renderHand(RenderPlayerAether.java:509)
	at net.aetherteam.aether.client.ClientGuiListener.onRenderHand(ClientGuiListener.java:67)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_31_ClientGuiListener_onRenderHand_RenderHandEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:266)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1358)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Psiiche'/232, l='MpServer', x=-295.39, y=71.62, z=-240.40]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-248,64,-184), Chunk: (at 8,4,8 in -16,-12; contains blocks -256,0,-192 to -241,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1978096 game time, 2038723 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityLeashKnot['entity.LeashKnot.name'/231, l='MpServer', x=-257.50, y=71.50, z=-276.50], EntityClientPlayerMP['Psiiche'/232, l='MpServer', x=-295.39, y=71.62, z=-240.40]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 203519504 bytes (194 MB) / 463470592 bytes (442 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 1 total; -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (minecraftforge-1.7.10-10.13.4.1448.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (minecraftforge-1.7.10-10.13.4.1448.jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar) 
	UCHIJAAAA	aether{1.7.10-1.5.1} [Aether II] (aether-1.7.10-1.5.1.jar) 
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.3062' Renderer: 'Intel(R) HD Graphics 3000'
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.3062, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Jess's Chroma Hills]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (4)

**Comment by Collin1971** [comment] 2015-10-12 13:24
Duplicate of #555.

**Closed by Collin1971** 2015-10-12 13:24 UTC

**Comment by Psiiche** [comment] 2015-10-12 13:26
I also found this in a separate log file, it mentions a "ticking player".

[08:48:08] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[08:48:08] [Server thread/INFO]: Generating keypair
[08:48:08] [Server thread/INFO]: Preparing start region for level 0
[08:48:09] [Server thread/INFO]: Preparing spawn area: 45%
[08:48:11] [Server thread/INFO]: Changing view distance to 5, from 10
[08:48:11] [Server thread/INFO]: Psiiche[local:E:d0879299] logged in with entity id 109707 at (-295.391739655006, 70.0, -240.40194864462532)
[08:48:11] [Server thread/INFO]: Psiiche joined the game
[08:48:12] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NullPointerException
	at net.aetherteam.aether.containers.inventory.InventoryAccessories.breakItem(InventoryAccessories.java:91) ~[InventoryAccessories.class:?]
	at net.aetherteam.aether.player.abilities.AbilityAccessories.damageItemStackIfWearing(AbilityAccessories.java:57) ~[AbilityAccessories.class:?]
	at net.aetherteam.aether.player.abilities.AbilityAccessories.onUpdate(AbilityAccessories.java:74) ~[AbilityAccessories.class:?]
	at net.aetherteam.aether.player.PlayerAether.onUpdate(PlayerAether.java:288) ~[PlayerAether.class:?]
	at com.gildedgames.util.player.common.PlayerEventHandler.onLivingUpdate(PlayerEventHandler.java:70) ~[PlayerEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_20_PlayerEventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	... 5 more
[08:48:12] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Jess\AppData\Roaming\.aether\profiles\1.7.10-1.5.1\crash-reports\crash-2015-10-12_08.48.12-server.txt
[08:48:12] [Server thread/INFO]: Stopping server
[08:48:12] [Server thread/INFO]: Saving players
[08:48:12] [Server thread/INFO]: Saving worlds
[08:48:12] [Server thread/INFO]: Saving chunks for level 'Mesa Village'/Overworld
[08:48:12] [Server thread/INFO]: Saving chunks for level 'Mesa Village'/Nether
[08:48:12] [Server thread/INFO]: Saving chunks for level 'Mesa Village'/The End
[08:48:12] [Server thread/INFO]: Saving chunks for level 'Mesa Village'/Dungeons
[08:48:12] [Server thread/INFO]: Saving chunks for level 'Mesa Village'/Aether

**Comment by Psiiche** [comment] 2015-10-12 13:28
That other thread is issues with weather, not issues to a world not starting. As fas as I can remember no one was wearing Iron either (we have Zanite gear). If on the offchance someone was, where would I go to delete "playerdata" and try again?

**Comment by Collin1971** [comment] 2015-10-12 14:02
Your crash log is identical to the one found in #555. (and, even after removing the weather mod he still encountered the issue)

Regardless of what causes the issue, the core issue is still the same, we have an issue in a very specific bit of our code that causes a very wide array of issues.
