### ISSUE TITLE
Achievements between mods problem

### ISSUE THREAD

**Issue by Zaltora** [gildedgames/aether-issues#386] opened 2015-02-16 13:59 UTC
When we play with aether II and others mods, achievement button show only  "minecraft" and "the aether II" achievements, others mods are hided like "hardcore ender expansion" or "twilight forest".

my mod list => the aether II, thaumcraft, twilight forest, HEE, Optifine, redstone paste, craftguide ;
forge 10.13.2.1291 ;

**Comment by xJonL** [comment] 2015-02-16 16:26
Duplicate of:
https://github.com/gildedgames/aether-issues/issues/371

**Closed by xJonL** 2015-02-16 16:26 UTC
Labels: duplicate
