### ISSUE TITLE
Rendering Crash

### ISSUE THREAD

**Issue by EVDESTROY** [gildedgames/aether-issues#563] opened 2015-10-06 11:45 UTC
So basically, when I open up Aether II it works fine. However, going into the world crashes me due to, I think, rendering problems. I will paste my crash report below, can't get in the game though. PLZ FIX!

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 10/6/15 6:39 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.aetherteam.aether.client.renders.entities.player.RenderPlayerAether.renderGloves(RenderPlayerAether.java:74)
	at net.aetherteam.aether.client.renders.entities.player.RenderPlayerAether.renderHand(RenderPlayerAether.java:509)
	at net.aetherteam.aether.client.ClientGuiListener.onRenderHand(ClientGuiListener.java:67)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_30_ClientGuiListener_onRenderHand_RenderHandEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:266)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1358)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.aetherteam.aether.client.renders.entities.player.RenderPlayerAether.renderGloves(RenderPlayerAether.java:74)
	at net.aetherteam.aether.client.renders.entities.player.RenderPlayerAether.renderHand(RenderPlayerAether.java:509)
	at net.aetherteam.aether.client.ClientGuiListener.onRenderHand(ClientGuiListener.java:67)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_30_ClientGuiListener_onRenderHand_RenderHandEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:266)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1358)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['EVDESTROY'/168097, l='MpServer', x=41.44, y=154.12, z=-24.96]]
	Chunk stats: MultiplayerChunkCache: 260, 260
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-12271,54,-4024), Chunk: (at 1,3,8 in -767,-252; contains blocks -12272,0,-4032 to -12257,255,-4017), Region: (-24,-8; contains chunks -768,-256 to -737,-225, blocks -12288,0,-4096 to -11777,255,-3585)
	Level time: 326358568 game time, 29013500 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 43 total; [EntityClientPlayerMP['EVDESTROY'/168097, l='MpServer', x=41.44, y=154.12, z=-24.96], EntityWitherSkull['entity.WitherSkull.name'/91072, l='MpServer', x=82.13, y=204.50, z=0.44], EntityVillager['Villager'/974, l='MpServer', x=54.50, y=146.00, z=-26.50], EntityVillager['§aEdison'/975, l='MpServer', x=55.78, y=149.00, z=-27.44], EntityWitherSkull['entity.WitherSkull.name'/99731, l='MpServer', x=4.72, y=210.00, z=0.31], EntityHorse['§m-------------------------'/99730, l='MpServer', x=4.72, y=210.23, z=0.31], EntityWitherSkull['entity.WitherSkull.name'/99733, l='MpServer', x=4.72, y=209.75, z=0.31], EntityHorse['Welcome to the §bAether Official Server§f!'/99732, l='MpServer', x=4.72, y=209.98, z=0.31], EntitySheep['Ona's Sheep'/982, l='MpServer', x=48.22, y=149.00, z=-45.31], EntityWitherSkull['entity.WitherSkull.name'/99735, l='MpServer', x=4.72, y=209.50, z=0.31], EntityHorse['Make sure to read the §4/rules'/99734, l='MpServer', x=4.72, y=209.73, z=0.31], EntityWitherSkull['entity.WitherSkull.name'/99737, l='MpServer', x=4.72, y=209.25, z=0.31], EntityHorse['New to the §bAether II§f?'/91033, l='MpServer', x=2.50, y=210.23, z=-5.59], EntityHorse['and follow the signs to get started!'/99736, l='MpServer', x=4.72, y=209.48, z=0.31], EntityWitherSkull['entity.WitherSkull.name'/99739, l='MpServer', x=4.72, y=209.00, z=0.31], EntityHorse['Check out the Aether Wiki!'/91035, l='MpServer', x=2.50, y=209.98, z=-5.59], EntityHorse['§m-------------------------'/99738, l='MpServer', x=4.72, y=209.23, z=0.31], EntityWitherSkull['entity.WitherSkull.name'/91034, l='MpServer', x=2.50, y=210.00, z=-5.59], EntityWitherSkull['entity.WitherSkull.name'/99741, l='MpServer', x=2.66, y=210.00, z=6.47], EntityHorse['§baether.wikia.com'/91037, l='MpServer', x=2.50, y=209.73, z=-5.59], EntityHorse['§6Halloween§f is upon us!'/99740, l='MpServer', x=2.66, y=210.23, z=6.47], EntityWitherSkull['entity.WitherSkull.name'/91036, l='MpServer', x=2.50, y=209.75, z=-5.59], EntityWitherSkull['entity.WitherSkull.name'/99743, l='MpServer', x=2.66, y=209.75, z=6.47], EntityHorse['Explore the redesigned spawn'/99742, l='MpServer', x=2.66, y=209.98, z=6.47], EntityWitherSkull['entity.WitherSkull.name'/91038, l='MpServer', x=2.50, y=209.50, z=-5.59], EntityWitherSkull['entity.WitherSkull.name'/99745, l='MpServer', x=2.66, y=209.50, z=6.47], EntityHorse['and check out §aEdison's Candy Shop§f!'/99744, l='MpServer', x=2.66, y=209.73, z=6.47], EntityWitherSkull['entity.WitherSkull.name'/99747, l='MpServer', x=12.59, y=210.50, z=0.59], EntityHorse['^ ^ ^'/99746, l='MpServer', x=12.59, y=210.73, z=0.59], EntitySoaringWisp['Soaring Wisp'/168102, l='MpServer', x=41.44, y=152.50, z=-24.97], EntityWitherSkull['entity.WitherSkull.name'/99749, l='MpServer', x=12.59, y=210.25, z=0.59], EntityHorse['§bAether Portal'/99748, l='MpServer', x=12.59, y=210.48, z=0.59], EntityHorse['§aEdison§f has arrived for §6Halloween§f!'/91061, l='MpServer', x=51.53, y=205.23, z=-29.28], EntityHorse['He brings delicious §dcandy§f!'/91063, l='MpServer', x=51.53, y=204.98, z=-29.28], EntityWitherSkull['entity.WitherSkull.name'/91062, l='MpServer', x=51.53, y=205.00, z=-29.28], EntityHorse['... for a price!'/91065, l='MpServer', x=51.53, y=204.73, z=-29.28], EntityWitherSkull['entity.WitherSkull.name'/91064, l='MpServer', x=51.53, y=204.75, z=-29.28], EntityHorse['Now then, just step through'/91067, l='MpServer', x=82.13, y=205.23, z=0.44], EntityWitherSkull['entity.WitherSkull.name'/91066, l='MpServer', x=51.53, y=204.50, z=-29.28], EntityHorse['the §bAether Portal§f to'/91069, l='MpServer', x=82.13, y=204.98, z=0.44], EntityWitherSkull['entity.WitherSkull.name'/91068, l='MpServer', x=82.13, y=205.00, z=0.44], EntityHorse['begin your adventure!'/91071, l='MpServer', x=82.13, y=204.73, z=0.44], EntityWitherSkull['entity.WitherSkull.name'/91070, l='MpServer', x=82.13, y=204.75, z=0.44]]
	Retry entities: 0 total; []
	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 148323992 bytes (141 MB) / 298864640 bytes (285 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJA	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar) 
	UCHIJA	aether{1.7.10-1.5.1} [Aether II] (aether-1.7.10-1.5.1.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4252' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.7.10-Forge10.13.4.1492-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4252, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by xJonL** [comment] 2015-10-06 13:30
Duplicate of #555

**Closed by xJonL** 2015-10-06 13:30 UTC
Labels: Crash
