### ISSUE TITLE
destroying top halves of skyroot doors gives you two skyroot doors

### ISSUE THREAD

**Issue by Flog301** [gildedgames/aether-issues#538] opened 2015-09-04 18:36 UTC
when destroying the top halves of skyroot doors with anything you can get two skyroot doors, thereby duplicating them. this still works even when you place the duplicated doors down.

**Comment by Tamaized** [comment] 2015-09-04 18:58
Does anyone even bother reading other issues?
#532, #510, #502
Anyway, they said this is fixed in the next version.

**Comment by Collin1971** [comment] 2015-09-04 19:31
Duplicate of #502, #510 and #532.

Please at least attempt to search for your issue.

**Closed by Collin1971** 2015-09-04 19:31 UTC
