### ISSUE TITLE
Crash related to expiring Accessories

### ISSUE THREAD

**Issue by wilkemeyer** [gildedgames/aether-issues#574] opened 2015-11-01 03:45 UTC
Hey,

it seems there's a problem (or maybe it's the combination of mods we're using) with expiring Accessories.

Everyone in screen gets a client crash in SMP, 
the server won't crash if the issue occurs.

Crashdump: http://pastebin.com/J7CwzstE

I know.. it's a huge modpack, but as the stacktrace shows, it's seems to be a missing nullcheck (or fail fired event)  in/from your code :), as i have no source access (and i haven't the time / motivation to decompile) i couldn't check it by myself.

**Comment by Collin1971** [comment] 2015-11-01 06:59
Duplicate of #553.

**Closed by Collin1971** 2015-11-01 06:59 UTC
