### ISSUE TITLE
Changing Dimensions duplicates health boosts from other mods/breaks botanias step-assist

### ISSUE THREAD

**Issue by DrasticDemise** [gildedgames/aether-issues#489] opened 2015-05-03 00:10 UTC
Hey! A bunch of people in my pack are reporting a bug in which health boosts duplicate from other mods when the Aether is installed.

It has been tested with the Artifacts mod and Botania. Neither of these mods alone have any issue, but when the Aether is included the health is duplicated.

Items used:
Any artifacts item with health boost
Ring of Odin(Botania)
Sojourners Sash/globe trotters sash (botania step assist)

It can't be a bauble issue because of the artifacts mod, and it only happens when changing dimensions.

**Comment by CherryHotaling** [comment] 2015-05-04 01:30
Duplicate of: https://github.com/gildedgames/aether-issues/issues/459

**Closed** 2015-05-05 12:00 UTC
Labels: duplicate
