### ISSUE TITLE
Crash when logging into the AOS

### ISSUE THREAD

**Issue by AndyPyro** [gildedgames/aether-issues#566] opened 2015-10-09 00:01 UTC
I recently started having this crash after I tried logging in today.
I can play singleplayer normally, the crash only occurs on the server.
Here is the crash log

---- Minecraft Crash Report ----
// You're mean.

Time: 10/8/15 6:13 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.aetherteam.aether.client.renders.entities.player.RenderPlayerAether.renderGloves(RenderPlayerAether.java:74)
	at net.aetherteam.aether.client.renders.entities.player.RenderPlayerAether.renderHand(RenderPlayerAether.java:509)
	at net.aetherteam.aether.client.ClientGuiListener.onRenderHand(ClientGuiListener.java:67)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_57_ClientGuiListener_onRenderHand_RenderHandEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:266)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1358)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.aetherteam.aether.client.renders.entities.player.RenderPlayerAether.renderGloves(RenderPlayerAether.java:74)
	at net.aetherteam.aether.client.renders.entities.player.RenderPlayerAether.renderHand(RenderPlayerAether.java:509)
	at net.aetherteam.aether.client.ClientGuiListener.onRenderHand(ClientGuiListener.java:67)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_57_ClientGuiListener_onRenderHand_RenderHandEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:266)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1358)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['AndyPyr0'/566260, l='MpServer', x=112958.19, y=56.62, z=415.29]]
	Chunk stats: MultiplayerChunkCache: 50, 50
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (112923,74,430), Chunk: (at 11,4,14 in 7057,26; contains blocks 112912,0,416 to 112927,255,431), Region: (220,0; contains chunks 7040,0 to 7071,31, blocks 112640,0,0 to 113151,255,511)
	Level time: 330383688 game time, 37132908 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 69 total; [EntityClientPlayerMP['AndyPyr0'/566260, l='MpServer', x=112958.19, y=56.62, z=415.29], EntityZephyr['Zephyr'/566297, l='MpServer', x=112956.43, y=59.83, z=402.20], EntityZephyr['Zephyr'/566298, l='MpServer', x=112943.51, y=-14.22, z=420.55], EntityMoa['Moa'/566299, l='MpServer', x=112944.69, y=64.00, z=431.47], EntityShadeOfArkenzus['Shade of Arkenzus'/566300, l='MpServer', x=112958.19, y=55.00, z=415.28], EntityAechorPlant['Aechor Plant'/566301, l='MpServer', x=112939.00, y=62.00, z=406.00], EntityMoa['Moa'/566302, l='MpServer', x=112950.13, y=5.00, z=393.09], EntityFlyingCow['Flying Cow'/566303, l='MpServer', x=112950.50, y=18.00, z=387.63], EntityFlyingCow['Flying Cow'/566294, l='MpServer', x=112959.28, y=50.00, z=400.47], EntityCockatrice['Cockatrice'/566295, l='MpServer', x=112957.50, y=62.00, z=411.50], EntityFlyingCow['Flying Cow'/566312, l='MpServer', x=112958.59, y=17.00, z=378.50], EntityAechorPlant['Aechor Plant'/566313, l='MpServer', x=112988.00, y=56.00, z=411.00], EntityMoa['Moa'/566314, l='MpServer', x=112945.88, y=64.00, z=432.88], EntityFlyingCow['Flying Cow'/566315, l='MpServer', x=112937.53, y=33.00, z=442.31], EntityMoa['Moa'/566316, l='MpServer', x=112941.03, y=48.00, z=441.78], EntityMoa['Moa'/566317, l='MpServer', x=112930.94, y=73.13, z=436.91], EntityCockatrice['Cockatrice'/566318, l='MpServer', x=112924.44, y=74.00, z=425.81], EntitySheepuff['Sheepuff'/566319, l='MpServer', x=112917.69, y=19.00, z=384.47], EntityFlyingCow['Flying Cow'/566304, l='MpServer', x=112951.59, y=18.00, z=389.47], EntityFlyingCow['Flying Cow'/566305, l='MpServer', x=112958.50, y=18.00, z=396.38], EntityFlyingCow['Flying Cow'/566306, l='MpServer', x=112945.34, y=20.00, z=396.50], EntityCockatrice['Cockatrice'/566307, l='MpServer', x=112964.34, y=62.00, z=410.59], EntityMoa['Moa'/566308, l='MpServer', x=112943.13, y=64.00, z=431.00], EntityFlyingCow['Flying Cow'/566309, l='MpServer', x=112971.03, y=33.00, z=390.19], EntityFlyingCow['Flying Cow'/566310, l='MpServer', x=112974.09, y=34.00, z=388.00], EntityMoa['Moa'/566311, l='MpServer', x=112913.53, y=62.00, z=402.41], EntitySheepuff['Sheepuff'/566328, l='MpServer', x=112917.47, y=19.00, z=382.34], EntityMoa['Moa'/566329, l='MpServer', x=112927.91, y=19.00, z=383.88], EntityFlyingCow['Flying Cow'/566330, l='MpServer', x=112981.50, y=33.00, z=381.53], EntityFlyingCow['Flying Cow'/566331, l='MpServer', x=112985.00, y=33.00, z=373.88], EntityPhyg['Phyg'/566332, l='MpServer', x=112989.78, y=34.00, z=376.31], EntityFlyingCow['Flying Cow'/566333, l='MpServer', x=112981.53, y=37.00, z=382.94], EntityFlyingCow['Flying Cow'/566334, l='MpServer', x=112984.97, y=33.00, z=375.16], EntityFlyingCow['Flying Cow'/566335, l='MpServer', x=112990.69, y=39.00, z=379.53], EntitySheepuff['Sheepuff'/566320, l='MpServer', x=112917.34, y=32.00, z=393.50], EntityMoa['Moa'/566321, l='MpServer', x=112915.00, y=32.00, z=395.97], EntityFlyingCow['Flying Cow'/566322, l='MpServer', x=112977.47, y=33.00, z=386.06], EntityFlyingCow['Flying Cow'/566323, l='MpServer', x=112979.53, y=47.00, z=395.66], EntityFlyingCow['Flying Cow'/566324, l='MpServer', x=112982.97, y=48.00, z=395.97], EntityMoa['Moa'/566325, l='MpServer', x=112918.38, y=57.00, z=444.03], EntityMoa['Moa'/566326, l='MpServer', x=112913.78, y=69.00, z=439.28], EntityMoa['Moa'/566327, l='MpServer', x=112912.59, y=72.00, z=432.22], EntityItem['item.Blue Moa Egg'/566344, l='MpServer', x=112911.88, y=71.13, z=430.91], EntityItem['item.Blue Moa Egg'/566345, l='MpServer', x=112908.63, y=69.13, z=430.19], EntityItem['item.White Moa Egg'/566346, l='MpServer', x=112910.34, y=71.13, z=430.16], EntityZephyr['Zephyr'/566347, l='MpServer', x=112906.88, y=160.06, z=417.22], EntityMoa['Moa'/566348, l='MpServer', x=112908.59, y=35.00, z=399.88], EntityMoa['Moa'/566349, l='MpServer', x=112912.09, y=10.00, z=452.06], EntityFlyingCow['Flying Cow'/566350, l='MpServer', x=113005.47, y=14.00, z=373.66], EntityFlyingCow['Flying Cow'/566351, l='MpServer', x=112996.50, y=33.00, z=378.47], EntityFlyingCow['Flying Cow'/566336, l='MpServer', x=112990.34, y=36.00, z=378.53], EntityMoa['Moa'/566337, l='MpServer', x=112989.28, y=35.00, z=377.50], EntityAechorPlant['Aechor Plant'/566338, l='MpServer', x=112896.00, y=59.00, z=410.00], EntityAechorPlant['Aechor Plant'/566339, l='MpServer', x=112896.00, y=59.00, z=408.00], EntityFlyingCow['Flying Cow'/566340, l='MpServer', x=113006.69, y=66.00, z=414.44], EntityMoa['Moa'/566341, l='MpServer', x=112901.75, y=63.00, z=419.03], EntityMoa['Moa'/566342, l='MpServer', x=112908.72, y=69.00, z=426.44], EntityMoa['Moa'/566343, l='MpServer', x=112911.50, y=71.00, z=430.41], EntityFlyingCow['Flying Cow'/566363, l='MpServer', x=112972.47, y=19.00, z=467.66], EntityMoa['Moa'/566364, l='MpServer', x=112970.09, y=19.00, z=471.91], EntityFlyingCow['Flying Cow'/566365, l='MpServer', x=112966.66, y=45.00, z=464.00], EntityFlyingCow['Flying Cow'/566352, l='MpServer', x=113006.28, y=37.00, z=381.50], EntityFlyingCow['Flying Cow'/566353, l='MpServer', x=112992.72, y=35.00, z=376.50], EntityMoa['Moa'/566354, l='MpServer', x=112911.16, y=71.00, z=433.59], EntityFlyingCow['Flying Cow'/566355, l='MpServer', x=113002.81, y=48.00, z=437.78], EntityFlyingCow['Flying Cow'/566356, l='MpServer', x=113011.28, y=69.00, z=391.03], EntityFlyingCow['Flying Cow'/566357, l='MpServer', x=112988.31, y=40.00, z=452.81], EntityFlyingCow['Flying Cow'/566369, l='MpServer', x=113009.53, y=14.00, z=374.66], EntityPhyg['Phyg'/566370, l='MpServer', x=113021.72, y=57.00, z=435.34]]
	Retry entities: 0 total; []
	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 120731856 bytes (115 MB) / 319385600 bytes (304 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	CodeChickenCore{1.0.2.11} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.2.15} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.2.15-universal.jar) 
	UCHIJA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJA	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util-1.7.10-1.7.jar) 
	UCHIJA	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCHIJA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJA	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) 
	UCHIJA	aether{1.7.10-1.5.1} [Aether II] (aether-1.7.10-1.5.1.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.12198 Compatibility Profile Context 12.102.4.0' Renderer: 'AMD Radeon HD 6310 Graphics'
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6310 Graphics GL version 4.2.12198 Compatibility Profile Context 12.102.4.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Andy's Pack V.Ae.1.7.10-4.1.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Collin1971** [comment] 2015-10-09 00:05
Duplicate of #555.

**Closed by Collin1971** 2015-10-09 00:05 UTC
