### ISSUE TITLE
valkyrie lance crash

### ISSUE THREAD

**Issue by JimmyJam20** [gildedgames/aether-issues#530] opened 2015-08-15 16:59 UTC
Hitting a Ghast fire ball with the Valkyrie Lance crashed the game.

**Comment by Collin1971** [comment] 2015-08-15 18:53
Duplicate of #501.

**Closed by Collin1971** 2015-08-15 18:53 UTC

**Comment by JimmyJam20** [comment] 2015-08-15 21:28
Sorry i didn't have time to see if it had been reported.
