### ISSUE TITLE
Disconnection when enterin Aether

### ISSUE THREAD

**Issue by Cr0wmaster** [gildedgames/aether-issues#423] opened 2015-02-24 14:34 UTC
This happens on multiplayer, every time i go from overworld to aether get disconnected from the server i play. I only use Aether mod, nothing more.

**Comment by Collin1971** [comment] 2015-02-24 18:38
Possible duplicate of #382.

Please re-open this issue when you obtain the crash log and have made sure this issue isn't related to #382.

**Closed by Collin1971** 2015-02-24 18:38 UTC
