### ISSUE TITLE
Party Tab Not Showing Up For People

### ISSUE THREAD

**Issue by GreatAssassin02** [gildedgames/aether-issues#528] opened 2015-08-15 07:37 UTC
The tab that im suppose to see isn't showing its face..

**Comment by Collin1971** [comment] 2015-08-15 15:59
Do you have any other mods installed? If so, could you please list them?

**Comment by xJonL** [comment] 2015-08-22 04:09
There is a mod compatibility issue with TabbyChat as Aether overrides the chat to place the tabs at the top of your screen, but then TabbyChat overrides it it too and completely removes it. If you have that mod installed you'd have to remove it to use the tabs.

**Comment by xJonL** [comment] 2015-08-27 02:46
Duplicate of #478

**Closed by xJonL** 2015-08-27 02:46 UTC
Labels: Compatibility Issue
