### ISSUE TITLE
New update broke modpack

### ISSUE THREAD

**Issue by FishSauceGaming** [gildedgames/aether-issues#549] opened 2015-09-19 03:27 UTC
Hello, the version of Aether 2 prior to 1.5 worked fine in my mod pack and there was no crashes. When I updated the mod to 1.5 my game started crashing. When I reverted the mod back, there were no issues. 

Here is a crash report: http://pastebin.com/EjMqyEbx

**Comment by Collin1971** [comment] 2015-09-19 03:30
Duplicate of #543.

**Closed by Collin1971** 2015-09-19 03:30 UTC
